### ISSUE TITLE
[RFC] 移除 站点配置中的 timezoneOffset 配置项

### ISSUE THREAD

**Issue by Rhilip** [pt-plugins/PT-depiler#206]
在PTPP中，我们添加了 timezoneOffset 配置项来作为时区转换的用户自定义项。
这在使用 day.js 进行解析时并没有太大关系。

然而在目前的时间解析中，我们默认使用了以下方法，将 `new Date()` 作为基类，则会导致在解析时就默认带上了时区配置

```ts
export function parseValidTimeString(query: string, formatString: string[] = []): number | string {
  for (const f of [...formatString, "yyyy-MM-dd'T'HH:mm:ssXXX", "yyyy-MM-dd HH:mm:ss", "yyyy-MM-dd HH:mm:ss.SSS"]) {
    let time = parse(query, f, new Date());
    if (isValid(time)) {
      return +time;
    }
  }
  return query;
}
```

在这种情况下，额外再在解析过程中进行一次时区偏移转换，可能反而会导致在聚合搜索结果中的时间显示错误

```
    // 仅当设置了时区偏移时，才进行转换
    if (this.metadata.timezoneOffset) {
      torrent.time = parseTimeWithZone(torrent.time as unknown as string, this.metadata.timezoneOffset);
    }
```

此外，以 NexusPHP 为模板的站点，因为使用的是服务器时间，并没有调整时区的必要性。
如实在需要，也可以和Jackett一样通过下面方式硬编码。

```yaml
    # [REQUIRED] publish date (if the site does not provide a date for all results, then a default of "now" should be used)
    # if the site can only provide a rows: dateheaders: selector then you can omit the date field.
    # The relevant time zone abbreviation (e.g. CST, CET, GMT, MSK, etc.) should also be added as a comment,
    # or the comment "auto adjusted by site account profile" used if appropriate
    date:
      selector: td:nth-child(4) > span[title]
      attribute: title
      filters:
        # append the timezone used by the tracker
        - name: append
          args: " +08:00" # CST
        - name: dateparse 
          args: "yyyy-MM-ss HH:mm:ss zzz"
```
